# Travis CI configuration for Tesseract
sudo: false
notifications:
  email: false
language: cpp

os: linux
dist:
  - xenial
  - bionic
  - focal
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libarchive-dev
      - libpango1.0-dev
      - libicu-dev
env:
  - LEPT_VER=1.80.0
cache:
  directories:
    - leptonica-$LEPT_VER

install:
  - if test ! -d leptonica-$LEPT_VER/src; then curl -Ls https://github.com/DanBloomberg/leptonica/archive/$LEPT_VER.tar.gz | tar -xz; fi
  - if test ! -d leptonica-$LEPT_VER/usr; then cmake -Hleptonica-$LEPT_VER -Bleptonica-$LEPT_VER/build -DCMAKE_INSTALL_PREFIX=leptonica-$LEPT_VER/usr; fi
  - if test ! -e leptonica-$LEPT_VER/usr/lib/libleptonica.so; then make -C leptonica-$LEPT_VER/build install; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DLeptonica_DIR=leptonica-$LEPT_VER/build -DSW_BUILD=OFF
  - make training
  - sudo make install
  - sudo make training-install

after_script:
  - tesseract -v
  - text2image -v
  - lstmtraining -v

###    - os: osx
###osx_image: xcode12.2
###before_cache:
### - brew cleanup
###cache:
###  ccache: true
###  directories:
###    - $HOME/Library/Caches/Homebrew
###before_install:
###  - brew install ccache
###install:
###  - brew install ninja libtiff leptonica libarchive pango cairo icu4c
###script:
###  - |
###    export PKG_CONFIG_PATH=$(brew --prefix)/opt/icu4c/lib/pkgconfig:$(brew --prefix)/opt/libarchive/lib/pkgconfig:/$(brew --prefix)/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH
###    mkdir build
###    mkdir inst
###    cmake \
###   -S . \
###   -B build \
###   -DCMAKE_BUILD_TYPE=Release \
###   -G Ninja \
###   -DCMAKE_INSTALL_PREFIX:PATH=inst
###    cmake --build build --config Release --target install

