name: linuxonly

on:
  #push:
  schedule:
    # every day
    - cron: 0 0 * * *

jobs:
  build-gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        gcc_version: [ 10, 9, 8, 7, 6, 5 ]
        build_type: [ Release, Debug ]
        exclude:
             - { gcc_version: 5, os: ubuntu-20.04 }
             - { gcc_version: 6, os: ubuntu-20.04 }

    steps:
      - name: Install compiler
        run: sudo apt-get install -y gcc-${{ matrix.gcc_version }} g++-${{ matrix.gcc_version }}
          
      - name: Install dependencies
        run: sudo apt-get install libleptonica-dev libpango1.0-dev -y

      - name: Checkout
        uses: actions/checkout@v2
         
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -D CMAKE_C_COMPILER=gcc-${{ matrix.gcc_version }} -D CMAKE_CXX_COMPILER=g++-${{ matrix.gcc_version }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

  build-clang:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        clang_version: [ 10, 9, 8, 7 ]
        build_type: [ Release, Debug ]

    steps:
      - name: Install compiler
        run: sudo apt-get install -y clang-${{ matrix.clang_version }}

      - name: Install dependencies
        run: sudo apt-get install libleptonica-dev libpango1.0-dev -y

      - name: Checkout
        uses: actions/checkout@v2
         
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -D CMAKE_C_COMPILER=clang-${{ matrix.clang_version }} -D CMAKE_CXX_COMPILER=clang++-${{ matrix.clang_version }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
        
